"use client";

import { useCallback, useEffect, useState } from "react";
import { WEEKDAYS } from "@/lib/config";
import { Btn, Card, PageHead, Field, Tag, readError } from "./ui";

type Day = {
  iso: string;
  label: string;
  capacity: number;
  startTime: string;
  endTime: string;
  cutoffIso: string | null;
  closed: boolean;
  confirmed: boolean;
  open: boolean;
  note: string | null;
  maxPerOrder: number | null;
  taken: number;
  left: number;
  specialLeft: number;
  specialCapacity: number;
  archived: boolean;
  outstanding: number;
  held: number;
  fromSlot: string | null;
};
type Slot = {
  weekday: number;
  capacity: number;
  startTime: string;
  endTime: string;
  active: boolean;
};

/** datetime-local wants "YYYY-MM-DDTHH:mm" in the browser's own timezone. */
const forInput = (iso: string | null) => {
  if (!iso) return "";
  const d = new Date(iso);
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
};

export function DaysManager({ flash }: { flash: (m: string) => void }) {
  const [days, setDays] = useState<Day[]>([]);
  const [slots, setSlots] = useState<Slot[]>([]);
  const [defaults, setDefaults] = useState({
    capacity: 32,
    start: "2:00 PM",
    end: "4:00 PM",
  });
  const [newDate, setNewDate] = useState("");
  const [warning, setWarning] = useState<string | null>(null);
  const [maxSlices, setMaxSlices] = useState("");

  const load = useCallback(async () => {
    const [d, s] = await Promise.all([
      fetch("/api/admin/days"),
      fetch("/api/admin/settings"),
    ]);
    if (d.ok) {
      const data = await d.json();
      setDays(data.days);
      setSlots(data.slots);
      setDefaults(data.defaults);
      setWarning(data.warning ?? null);
    }
    if (s.ok) setMaxSlices(String((await s.json()).maxPerOrder));
    if (!d.ok) flash(await readError(d));
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  async function saveDay(
    iso: string,
    patch: Partial<Day> & { cutoffIso?: string | null; archived?: boolean }
  ) {
    const r = await fetch("/api/admin/days", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ iso, ...patch }),
    });
    if (!r.ok) flash(await readError(r));
    load();
  }

  async function addOneOff() {
    if (!newDate) return;
    await saveDay(new Date(`${newDate}T00:00:00Z`).toISOString(), {
      capacity: defaults.capacity,
      startTime: defaults.start,
      endTime: defaults.end,
      confirmed: false,
    });
    setNewDate("");
    flash("Date added — set the cut-off, then confirm it");
  }

  async function removeDay(d: Day) {
    if (!confirm(`Remove ${d.label} completely? This can't be undone.`)) return;
    const r = await fetch(
      `/api/admin/days?iso=${encodeURIComponent(d.iso)}`,
      { method: "DELETE" }
    );
    if (!r.ok) {
      flash(await readError(r));
      load();
      return;
    }

    const result = await r.json();

    // A date generated by the weekly pattern comes straight back unless the
    // weekday is switched off — so offer that rather than leaving you
    // deleting the same date over and over.
    if (result.fromWeekday !== null && result.fromWeekday !== undefined) {
      const name = WEEKDAYS[result.fromWeekday];
      if (
        confirm(
          `${d.label} came from your weekly ${name} pattern, so it will be recreated. Turn ${name}s off as well?`
        )
      ) {
        await saveSlot(result.fromWeekday, { active: false });
      }
    }

    if (!result.remembered)
      flash(
        "Deleted, but it may reappear — run 'npm run db:push' so deletions can be remembered."
      );
    else if (result.testOrdersRemoved > 0)
      flash(`Deleted, along with ${result.testOrdersRemoved} test order(s)`);
    else flash("Date removed");

    load();
  }

  async function saveSlot(weekday: number, patch: Partial<Slot>) {
    const existing = slots.find((s) => s.weekday === weekday);
    const r = await fetch("/api/admin/slots", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        weekday,
        capacity: existing?.capacity ?? defaults.capacity,
        startTime: existing?.startTime ?? defaults.start,
        endTime: existing?.endTime ?? defaults.end,
        active: true,
        ...patch,
      }),
    });
    if (!r.ok) flash(await readError(r));
    load();
  }

  async function saveMax() {
    const r = await fetch("/api/admin/settings", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ maxPerOrder: Number(maxSlices) }),
    });
    if (!r.ok) return flash(await readError(r));
    flash(`Max ${maxSlices} slices per order`);
  }

  /** Deleted dates are remembered so the schedule can't recreate them. This
   *  forgets them and rebuilds from your weekly pattern. */
  async function restore() {
    const r = await fetch("/api/admin/days/restore", { method: "POST" });
    if (!r.ok) return flash(await readError(r));
    const d = await r.json();
    flash(
      d.made > 0
        ? `Restored ${d.made} date${d.made === 1 ? "" : "s"}`
        : "Nothing to restore — check a weekday is switched on above."
    );
    load();
  }

  const waiting = days.filter((d) => !d.confirmed).length;

  return (
    <>
      <PageHead
        title="Collection Dates"
        note="Dates, times, slice counts and cut-offs."
      />

      {warning && (
        <Card className="mb-5 border-bad/40 bg-bad-light">
          <p className="text-[15px] text-ink">{warning}</p>
        </Card>
      )}

      {days.length === 0 && (
        <Card className="mb-5 border-gold/40 bg-gold-light">
          <p className="text-[15px] text-ink">
            No dates here. If you deleted some while testing, they&apos;re
            being remembered as deleted so the weekly pattern can&apos;t put
            them back.
          </p>
          <div className="mt-3">
            <Btn variant="gold" onClick={restore}>
              Restore this week&apos;s dates
            </Btn>
          </div>
        </Card>
      )}

      {waiting > 0 && (
        <Card className="mb-5 border-gold/40 bg-gold-light">
          <p className="text-[15px] text-ink">
            {waiting} date{waiting === 1 ? "" : "s"} waiting to be confirmed.
            Nothing can be ordered until you release them.
          </p>
        </Card>
      )}

      {/* order limit + one-off date */}
      <div className="grid gap-4 md:grid-cols-2">
        <Card>
          <h2 className="font-display text-xl text-ink">
            Default order limit
          </h2>
          <div className="mt-3 flex items-end gap-3">
            <Field
              label="Max slices per order"
              value={maxSlices}
              onChange={(v) => setMaxSlices(v.replace(/\D/g, ""))}
              className="w-32"
            />
            <Btn onClick={saveMax}>Save</Btn>
          </div>
          <p className="mt-2 text-[12px] text-muted">
            Used by any date that doesn&apos;t set its own &ldquo;Max per
            order&rdquo; below. The step-down near sell-out still applies on
            top.
          </p>
        </Card>

        <Card>
          <h2 className="font-display text-xl text-ink">
            Add a one-off date
          </h2>
          <div className="mt-3 flex items-end gap-3">
            <label className="block">
              <span className="mb-1.5 block text-[13px] font-semibold text-ink">
                Date
              </span>
              <input
                type="date"
                value={newDate}
                onChange={(e) => setNewDate(e.target.value)}
                className="rounded-btn border border-field bg-paper px-3.5 py-2.5 text-[15px] text-ink focus:border-gold focus:outline-none focus:ring-4 focus:ring-gold/15"
              />
            </label>
            <Btn variant="gold" onClick={addOneOff} disabled={!newDate}>
              Add Date
            </Btn>
          </div>
        </Card>
      </div>

      {/* recurring */}
      <Card className="mt-4">
        <div className="flex flex-wrap items-baseline justify-between gap-2">
          <h2 className="font-display text-xl text-ink">Every week</h2>
          <button
            onClick={restore}
            className="text-[13px] font-semibold text-gold-hover underline underline-offset-4"
          >
            Restore deleted dates
          </button>
        </div>
        <p className="mt-1 text-[13px] text-ink2">
          Creates this week&apos;s dates for you to confirm. Nothing is
          generated beyond the current week.
        </p>
        <div className="mt-3 flex flex-wrap gap-2">
          {/* Monday first — WEEKDAYS is indexed by the JavaScript day number,
              where 0 is Sunday, so the order is set here rather than there. */}
          {[1, 2, 3, 4, 5, 6, 0].map((i) => {
            const name = WEEKDAYS[i];
            const on = slots.some((s) => s.weekday === i && s.active);
            return (
              <button
                key={i}
                onClick={() => saveSlot(i, { active: !on })}
                className={[
                  "rounded-btn px-4 py-2 text-sm font-semibold transition-colors",
                  on
                    ? "bg-navy text-white"
                    : "bg-cream-beige text-ink2 hover:bg-cream-warm",
                ].join(" ")}
              >
                {name.slice(0, 3)}
              </button>
            );
          })}
        </div>

        {slots
          .filter((s) => s.active)
          .sort((a, b) => ((a.weekday + 6) % 7) - ((b.weekday + 6) % 7))
          .map((s) => (
            <div
              key={s.weekday}
              className="mt-4 grid gap-3 border-t border-line pt-4 sm:grid-cols-4"
            >
              <p className="self-center font-semibold text-ink">
                {WEEKDAYS[s.weekday]}s
              </p>
              <Commit
                label="Slices"
                value={String(s.capacity)}
                onCommit={(v) => saveSlot(s.weekday, { capacity: Number(v) || 0 })}
              />
              <Commit
                label="From"
                value={s.startTime}
                onCommit={(v) => saveSlot(s.weekday, { startTime: v })}
              />
              <Commit
                label="Until"
                value={s.endTime}
                onCommit={(v) => saveSlot(s.weekday, { endTime: v })}
              />
            </div>
          ))}
      </Card>

      {/* the dates */}
      <div className="mt-5 space-y-4">
        {days.map((d) => (
          <Card key={d.iso} className={d.confirmed && d.open ? "" : "bg-cream-warm"}>
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div>
                <h3 className="font-display text-xl text-ink">{d.label}</h3>
                <div className="mt-1.5 flex flex-wrap gap-2">
                  <Tag tone="gold">{d.taken} sold</Tag>
                  <Tag>{d.left} left</Tag>
                  {!d.confirmed && <Tag tone="warn">Not confirmed</Tag>}
                  {d.held > 0 && (
                    <Tag tone="warn">
                      {d.held} being paid for
                    </Tag>
                  )}
                  {d.specialCapacity > 0 && (
                    <Tag tone="good">
                      +{d.specialLeft} of {d.specialCapacity} special
                    </Tag>
                  )}
                  {d.confirmed && d.closed && <Tag tone="bad">Orders closed</Tag>}
                  {d.confirmed && !d.open && <Tag tone="bad">Paused</Tag>}
                </div>
              </div>

              <div className="flex flex-wrap items-center gap-2">
                {!d.confirmed ? (
                  <Btn
                    variant="gold"
                    disabled={!d.cutoffIso}
                    title={d.cutoffIso ? "" : "Set a cut-off first"}
                    onClick={() => saveDay(d.iso, { confirmed: true })}
                  >
                    Confirm &amp; open
                  </Btn>
                ) : (
                  <label className="flex items-center gap-2 text-sm text-ink2">
                    <input
                      type="checkbox"
                      checked={d.open}
                      onChange={(e) => saveDay(d.iso, { open: e.target.checked })}
                      className="h-4 w-4 accent-gold"
                    />
                    Open
                  </label>
                )}
                {/* Once nothing is outstanding the day has served its purpose
                    — archiving early just keeps the Orders screen clean. */}
                {d.taken > 0 && d.outstanding === 0 && (
                  <Btn
                    variant="ghost"
                    onClick={() => {
                      if (
                        !confirm(
                          `Archive ${d.label}? It moves out of Orders into the Archive, where everything stays visible. Nothing is deleted, and you can bring it back.`
                        )
                      )
                        return;
                      saveDay(d.iso, { archived: true });
                    }}
                  >
                    Archive now
                  </Btn>
                )}

                {d.taken > 0 && d.outstanding > 0 && (
                  <span className="text-[12px] text-muted">
                    {d.outstanding} still to collect
                  </span>
                )}

                <Btn variant="danger" onClick={() => removeDay(d)}>
                  Remove
                </Btn>
              </div>
            </div>

            <div className="mt-4 grid min-w-0 gap-3 border-t border-line pt-4 sm:grid-cols-2 lg:grid-cols-5">
              <Commit
                label="Slices available"
                value={String(d.capacity)}
                onCommit={(v) => saveDay(d.iso, { capacity: Number(v) || 0 })}
              />
              <Commit
                label="Max per order"
                value={d.maxPerOrder ? String(d.maxPerOrder) : ""}
                onCommit={(v) =>
                  saveDay(d.iso, { maxPerOrder: v ? Number(v) : null })
                }
              />
              <Commit
                label="From"
                value={d.startTime}
                onCommit={(v) => saveDay(d.iso, { startTime: v })}
              />
              <Commit
                label="Until"
                value={d.endTime}
                onCommit={(v) => saveDay(d.iso, { endTime: v })}
              />
              <CutoffField
                value={forInput(d.cutoffIso)}
                onCommit={(v) =>
                  saveDay(d.iso, {
                    cutoffIso: v ? new Date(v).toISOString() : null,
                  })
                }
              />
            </div>

            <Commit
              label="Note shown on the site (optional)"
              value={d.note ?? ""}
              onCommit={(v) => saveDay(d.iso, { note: v })}
              className="mt-3"
            />

            {d.capacity < d.taken && (
              <p className="mt-3 rounded-card border border-bad/40 bg-bad-light px-4 py-2.5 text-[13px] text-ink">
                Capacity is below the {d.taken} already sold. Nothing is
                cancelled and everyone keeps their order — it just means no
                more can be ordered, and the day shows as sold out.
              </p>
            )}

            {d.capacity > d.taken && d.confirmed && d.open && !d.closed && (
              <p className="mt-3 text-[12px] text-ink2">
                {d.left} more slice{d.left === 1 ? "" : "s"} on sale right now.
                Change &ldquo;Slices available&rdquo; above and the shop
                updates within 20 seconds.
              </p>
            )}

            <FlavourStock day={d} flash={flash} />

            {d.fromSlot && (
              <p className="mt-3 text-[12px] text-muted">
                Created by your weekly pattern. Switch that weekday off above
                if you don&apos;t want it each week.
              </p>
            )}

            {/* Not selling, but still to come: offer to put it back on sale. */}
            {d.confirmed && (d.closed || !d.open || d.left <= 0) && (
              <>
                <p className="mt-3 text-[13px] text-muted">
                  {d.closed
                    ? "Orders closed for this date."
                    : !d.open
                      ? "Paused — hidden from the shop."
                      : "Sold out."}
                </p>
                <Reopen day={d} onDone={load} flash={flash} />
              </>
            )}

            {!d.confirmed && (
              <p className="mt-3 text-[13px] text-gold-hover">
                {d.cutoffIso
                  ? "Check the date, times and cut-off, then confirm to open ordering."
                  : "Set when orders close before you can confirm — you bake the day before, so it can't take orders up to the morning."}
              </p>
            )}
          </Card>
        ))}
      </div>
    </>
  );
}

/** Saves on blur rather than on every keystroke. */
function Commit({
  label,
  value,
  onCommit,
  className = "",
}: {
  label: string;
  value: string;
  onCommit: (v: string) => void;
  className?: string;
}) {
  const [v, setV] = useState(value);
  useEffect(() => setV(value), [value]);
  return (
    <Field
      label={label}
      value={v}
      onChange={setV}
      onBlur={() => v !== value && onCommit(v)}
      className={className}
    />
  );
}


/**
 * Saves when you finish, not on every keystroke.
 *
 * Saving on change reloaded the whole list mid-entry, which rewrote the field
 * from the server before you'd typed the second digit — so 10:30 came out as
 * 01:03. Holding the value locally and committing on blur fixes it.
 */
function CutoffField({
  value,
  onCommit,
}: {
  value: string;
  onCommit: (v: string) => void;
}) {
  const [v, setV] = useState(value);
  useEffect(() => setV(value), [value]);

  return (
    <label className="block">
      <span className="mb-1.5 block text-[13px] font-semibold text-ink">
        Orders close
      </span>
      <input
        type="datetime-local"
        value={v}
        onChange={(e) => setV(e.target.value)}
        onBlur={() => v !== value && onCommit(v)}
        className="w-full min-w-0 max-w-full rounded-btn border border-field bg-paper px-2.5 py-2.5 text-[14px] text-ink focus:border-gold focus:outline-none focus:ring-4 focus:ring-gold/15 sm:px-3.5 sm:text-[15px]"
      />
      {v !== value && (
        <span className="mt-1 block text-[12px] text-gold-hover">
          Click away to save
        </span>
      )}
    </label>
  );
}


/**
 * Cakes come out in eights, so an odd number of slices ordered always leaves
 * spares. This works out how many, and reopens the day for a few hours to
 * sell them.
 */
function Reopen({
  day,
  onDone,
  flash,
}: {
  day: Day;
  onDone: () => void;
  flash: (m: string) => void;
}) {
  const [info, setInfo] = useState<{
    taken: number;
    wholeCakes: number;
    capacity: number;
    available: number;
    spares: number;
  } | null>(null);
  const [hours, setHours] = useState("3");
  const [release, setRelease] = useState("");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    fetch(`/api/admin/days/reopen?iso=${encodeURIComponent(day.iso)}`)
      .then((r) => (r.ok ? r.json() : null))
      .then(setInfo);
  }, [day.iso]);

  if (!info) return null;

  async function go() {
    setBusy(true);
    const r = await fetch("/api/admin/days/reopen", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        iso: day.iso,
        hours: Number(hours) || 3,
        release: release ? Number(release) : undefined,
      }),
    });
    setBusy(false);
    if (!r.ok) return flash(await readError(r));
    const d = await r.json();
    flash(`Reopened — ${d.available} slice(s) on sale`);
    onDone();
  }

  return (
    <div className="mt-3 rounded-card border border-gold/40 bg-gold-light px-4 py-3">
      <p className="text-[15px] leading-relaxed text-ink">
        <strong>
          {info.available} slice{info.available === 1 ? "" : "s"} unsold for
          this date.
        </strong>
        <span className="mt-1 block text-[13px] text-ink2">
          {info.taken} ordered so far, which needs {info.wholeCakes} whole cake
          {info.wholeCakes === 1 ? "" : "s"}
          {info.spares > 0 && (
            <>
              {" "}
              — so {info.spares} slice{info.spares === 1 ? "" : "s"} of that
              would go spare
            </>
          )}
          . Day capacity is {info.capacity}. Cancellations and no-shows put
          their slices back automatically.
        </span>
      </p>

      <div className="mt-3 flex flex-wrap items-end gap-3">
        <label className="block">
          <span className="mb-1.5 block text-[13px] font-semibold text-ink">
            Slices to release
          </span>
          <input
            inputMode="numeric"
            value={release}
            onChange={(e) => setRelease(e.target.value.replace(/\D/g, ""))}
            placeholder={String(info.spares || info.available)}
            className="w-24 rounded-btn border border-field bg-paper px-3 py-2 text-[15px] text-ink focus:border-gold focus:outline-none"
          />
        </label>

        <label className="block">
          <span className="mb-1.5 block text-[13px] font-semibold text-ink">
            Reopen for
          </span>
          <span className="flex items-center gap-2">
            <input
              inputMode="numeric"
              value={hours}
              onChange={(e) => setHours(e.target.value.replace(/\D/g, ""))}
              onBlur={() => setHours((v) => (v === "" ? "3" : v))}
              className="w-16 rounded-btn border border-field bg-paper px-3 py-2 text-[15px] text-ink focus:border-gold focus:outline-none"
            />
            <span className="text-[15px] text-ink2">hours</span>
          </span>
        </label>

        <Btn variant="gold" onClick={go} disabled={busy}>
          {busy ? "Reopening…" : "Reopen for orders"}
        </Btn>
      </div>

      <p className="mt-2 text-[12px] text-ink2">
        Capacity goes to{" "}
        {release ? info.taken + Number(release) : info.capacity}, so{" "}
        {release || info.available} more can be ordered. Existing orders
        aren&apos;t touched. Reopens until{" "}
        {new Date(Date.now() + (Number(hours) || 3) * 3600000).toLocaleString(
          "en-GB",
          { weekday: "short", hour: "2-digit", minute: "2-digit" }
        )}
        , and a note appears on the site. Post it on your socials — that&apos;s
        where these get sold.
      </p>
    </div>
  );
}


/**
 * How many of each flavour you're making on this particular date.
 *
 * Blank means "no separate stock for this date" — the flavour's own default
 * applies, and if that's blank too it's limited only by the day's total. So a
 * special can be 6 on Saturday and 12 on Sunday.
 */
function FlavourStock({
  day,
  flash,
}: {
  day: Day;
  flash: (m: string) => void;
}) {
  type Row = {
    id: string;
    name: string;
    dayStock: number | null;
    defaultStock: number | null;
    sold: number;
    left: number | null;
  };

  const [rows, setRows] = useState<Row[] | null>(null);
  const [open, setOpen] = useState(false);

  const load = useCallback(async () => {
    const r = await fetch(
      `/api/admin/days/stock?iso=${encodeURIComponent(day.iso)}`
    );
    if (r.ok) setRows((await r.json()).flavours);
  }, [day.iso]);

  useEffect(() => {
    if (open) load();
  }, [open, load]);

  async function save(flavourId: string, value: string) {
    const r = await fetch("/api/admin/days/stock", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        iso: day.iso,
        flavourId,
        stock: value === "" ? null : Number(value),
      }),
    });
    if (!r.ok) return flash(await readError(r));
    load();
  }

  const setCount = rows?.filter((r) => r.dayStock !== null).length ?? 0;

  return (
    <div className="mt-3 border-t border-line pt-3">
      <button
        onClick={() => setOpen((v) => !v)}
        className="text-[13px] font-semibold text-gold-hover underline underline-offset-4"
      >
        {open ? "Hide" : "Set"} flavour stock for this date
        {setCount > 0 && !open && ` (${setCount} set)`}
      </button>

      {open && (
        <>
          <p className="mt-2 text-[12px] text-ink2">
            How many of each you&apos;re making on this date. A flavour with
            its own number gets its own pool — those slices don&apos;t come out
            of the day&apos;s total. Leave blank and the flavour&apos;s own
            default applies; blank on both and it draws on the day&apos;s total
            like the rest.
          </p>

          {!rows && <p className="mt-2 text-sm text-ink2">Loading…</p>}

          <ul className="mt-3 space-y-2">
            {rows?.map((f) => (
              <li key={f.id} className="flex flex-wrap items-center gap-3">
                <span className="min-w-[8rem] grow text-[15px] text-ink">
                  {f.name}
                </span>

                <StockBox
                  value={f.dayStock === null ? "" : String(f.dayStock)}
                  placeholder={
                    f.defaultStock === null ? "No limit" : String(f.defaultStock)
                  }
                  onCommit={(v) => save(f.id, v)}
                />

                <span className="w-28 text-right text-[12px] text-ink2">
                  {f.sold} sold
                  {f.left !== null && ` · ${f.left} left`}
                </span>
              </li>
            ))}
          </ul>
        </>
      )}
    </div>
  );
}

/** Saves on blur, and an empty value clears the figure for this date. */
function StockBox({
  value,
  placeholder,
  onCommit,
}: {
  value: string;
  placeholder: string;
  onCommit: (v: string) => void;
}) {
  const [v, setV] = useState(value);
  useEffect(() => setV(value), [value]);
  return (
    <input
      inputMode="numeric"
      value={v}
      placeholder={placeholder}
      onChange={(e) => setV(e.target.value.replace(/\D/g, ""))}
      onBlur={() => v !== value && onCommit(v)}
      className="w-24 rounded-btn border border-field bg-paper px-3 py-2 text-[15px] text-ink placeholder:text-muted focus:border-gold focus:outline-none"
    />
  );
}
